### ISSUE TITLE
backup all branches

### ISSUE THREAD

**Issue by vsespb** [bocytko/git-backup#1]
Would be great to implement http://stackoverflow.com/questions/12129148/incremental-backups-with-git-bundle-for-all-branches
or to mention in docs that backup saves only master branch

**Comment by bocytko** [comment]
I updated the docs. Thanks for the hint. Feel free to submit a pull request for the SO solution.

**Comment by vsespb** [comment]
Looks like it will be pretty hard to do in in BASH/SH. So I hacked Perl script https://github.com/vsespb/git-incremental-backup which seems to work, at least in two tests for incremental backup of sereval branches.
